
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async addGame(name: string, modDir: string, stagingDir: string | null, modStructure: string) : Promise<Result<AddGameResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_game", { name, modDir, stagingDir, modStructure }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeGame(id: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_game", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async editGame(id: number, name: string, modDir: string, stagingDir: string, modStructure: string) : Promise<Result<AddGameResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("edit_game", { id, name, modDir, stagingDir, modStructure }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listGames() : Promise<Result<GameRecord[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_games") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run the startup integrity scan.
 * 
 * Checks:
 * 1. Any in-progress toggle journal entries (crash recovery needed)
 * 2. Enabled mods whose files are missing from the game directory
 * 3. Disabled mods whose files are missing from staging
 * 
 * IMPORTANT: Returns empty results -- not an error -- when no mods exist.
 * This is the intentional behavior on first launch (PITFALL-5 guard).
 */
async runIntegrityScan() : Promise<Result<IntegrityScanResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_integrity_scan") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Return type for add_game and edit_game.
 * - cross_drive_warning: staging folder is on a different drive than mod_dir (slower moves)
 * - has_existing_mods: mod_dir already contains .pak/.ucas/.utoc files the user may want to import
 */
export type AddGameResult = { game: GameRecord; cross_drive_warning: boolean; has_existing_mods: boolean }
/**
 * All error types that can be returned from Tauri commands.
 * Tagged union serialized as {"kind": "VariantName", "message": "..."} for frontend consumption.
 * Every variant has a String message for display.
 */
export type AppError = 
/**
 * std::io::Error that doesn't fit a more specific category
 */
{ kind: "IoError"; message: string } | 
/**
 * File or directory operation rejected — may need elevation
 */
{ kind: "PermissionDenied"; message: string } | 
/**
 * SQLite or tauri-plugin-sql error
 */
{ kind: "DatabaseError"; message: string } | 
/**
 * Requested game ID not found in DB
 */
{ kind: "GameNotFound"; message: string } | 
/**
 * Requested mod ID not found in DB
 */
{ kind: "ModNotFound"; message: string } | 
/**
 * Staging directory already claimed by another game/mod
 */
{ kind: "StagingDirConflict"; message: string } | 
/**
 * Staging path is on a different drive than the mod directory — not an error, a warning surfaced to UI
 */
{ kind: "CrossDriveWarning"; message: string } | 
/**
 * toggle_journal entry is in a state that cannot be automatically recovered
 */
{ kind: "JournalCorrupt"; message: string } | 
/**
 * serde_json serialization/deserialization failure
 */
{ kind: "SerializationError"; message: string } | 
/**
 * Catch-all
 */
{ kind: "Unknown"; message: string }
/**
 * A single file move pair tracked in the journal.
 * `done` is updated to true after each individual file is successfully moved.
 */
export type FilePair = { src: string; dst: string; done: boolean }
export type GameRecord = { id: number; name: string; mod_dir: string; staging_dir: string; mod_structure: string; requires_elevation: boolean }
/**
 * A journal entry returned by scan_incomplete().
 */
export type IncompleteJournalEntry = { id: number; mod_id: number; operation: string; files: FilePair[] }
export type IntegrityScanResult = { missing_from_game: ModRecord[]; missing_from_staging: ModRecord[]; incomplete_journals: IncompleteJournalEntry[] }
export type ModRecord = { id: number; game_id: number; name: string; enabled: boolean; staged_path: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
