
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async addGame(name: string, modDir: string, stagingDir: string | null, modStructure: string) : Promise<Result<AddGameResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_game", { name, modDir, stagingDir, modStructure }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeGame(id: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_game", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async editGame(id: number, name: string, modDir: string, stagingDir: string, modStructure: string) : Promise<Result<AddGameResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("edit_game", { id, name, modDir, stagingDir, modStructure }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listGames() : Promise<Result<GameRecord[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_games") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run the startup integrity scan.
 * 
 * Checks:
 * 1. Any in-progress toggle journal entries (crash recovery needed)
 * 2. Enabled mods whose files are missing from the game directory
 * 3. Disabled mods whose files are missing from staging
 * 
 * IMPORTANT: Returns empty results -- not an error -- when no mods exist.
 * This is the intentional behavior on first launch (PITFALL-5 guard).
 */
async runIntegrityScan() : Promise<Result<IntegrityScanResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_integrity_scan") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Import a mod from a zip archive: extract to staging, create DB records, return result.
 */
async importMod(gameId: number, zipPath: string, modName: string) : Promise<Result<ImportResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_mod", { gameId, zipPath, modName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listMods(gameId: number) : Promise<Result<ModRecord[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_mods", { gameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listModFiles(modId: number) : Promise<Result<FileEntry[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_mod_files", { modId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSubModsCmd(modId: number) : Promise<Result<SubModRecord[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_sub_mods_cmd", { modId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleModCmd(modId: number, enable: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_mod_cmd", { modId, enable }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleSubModCmd(subModId: number, enable: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_sub_mod_cmd", { subModId, enable }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteModCmd(modId: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_mod_cmd", { modId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkConflictsCmd(modId: number, gameId: number) : Promise<Result<ConflictInfo[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_conflicts_cmd", { modId, gameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Import loose files into a new mod: copy to staging, create DB records.
 */
async importLooseFiles(gameId: number, modName: string, files: LooseFileInput[]) : Promise<Result<ImportResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_loose_files", { gameId, modName, files }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Import loose files from a zip: extract, copy selected files to staging, create DB records.
 */
async importLooseZip(gameId: number, zipPath: string, modName: string, selectedFiles: LooseFileInput[]) : Promise<Result<ImportResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_loose_zip", { gameId, zipPath, modName, selectedFiles }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add files to an existing loose-file mod.
 */
async addFilesToMod(modId: number, files: LooseFileInput[]) : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_files_to_mod", { modId, files }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove a single file from a loose-file mod (deletes from staging/game dir and DB).
 */
async removeFileFromMod(fileEntryId: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_file_from_mod", { fileEntryId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveProfileCmd(gameId: number, name: string) : Promise<Result<ProfileRecord, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_profile_cmd", { gameId, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listProfilesCmd(gameId: number) : Promise<Result<ProfileRecord[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_profiles_cmd", { gameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteProfileCmd(profileId: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_profile_cmd", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadProfileCmd(profileId: number) : Promise<Result<ApplyProfileResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_profile_cmd", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Return type for add_game and edit_game.
 * - cross_drive_warning: staging folder is on a different drive than mod_dir (slower moves)
 * - has_existing_mods: mod_dir already contains .pak/.ucas/.utoc files the user may want to import
 */
export type AddGameResult = { game: GameRecord; cross_drive_warning: boolean; has_existing_mods: boolean }
/**
 * All error types that can be returned from Tauri commands.
 * Tagged union serialized as {"kind": "VariantName", "message": "..."} for frontend consumption.
 * Every variant has a String message for display.
 */
export type AppError = 
/**
 * std::io::Error that doesn't fit a more specific category
 */
{ kind: "IoError"; message: string } | 
/**
 * File or directory operation rejected — may need elevation
 */
{ kind: "PermissionDenied"; message: string } | 
/**
 * SQLite or tauri-plugin-sql error
 */
{ kind: "DatabaseError"; message: string } | 
/**
 * Requested game ID not found in DB
 */
{ kind: "GameNotFound"; message: string } | 
/**
 * Requested mod ID not found in DB
 */
{ kind: "ModNotFound"; message: string } | 
/**
 * Staging directory already claimed by another game/mod
 */
{ kind: "StagingDirConflict"; message: string } | 
/**
 * Staging path is on a different drive than the mod directory — not an error, a warning surfaced to UI
 */
{ kind: "CrossDriveWarning"; message: string } | 
/**
 * toggle_journal entry is in a state that cannot be automatically recovered
 */
{ kind: "JournalCorrupt"; message: string } | 
/**
 * serde_json serialization/deserialization failure
 */
{ kind: "SerializationError"; message: string } | 
/**
 * Catch-all
 */
{ kind: "Unknown"; message: string }
/**
 * Result of applying a profile, including any mods that were skipped (deleted since save).
 */
export type ApplyProfileResult = { skipped_mods: string[] }
export type ConflictInfo = { conflicting_mod_id: number; conflicting_mod_name: string; relative_path: string }
export type FileEntry = { id: number; mod_id: number; relative_path: string; sub_mod_id: number | null; destination_path: string | null }
/**
 * A single file move pair tracked in the journal.
 * `done` is updated to true after each individual file is successfully moved.
 */
export type FilePair = { src: string; dst: string; done: boolean }
export type GameRecord = { id: number; name: string; mod_dir: string; staging_dir: string; mod_structure: string; requires_elevation: boolean }
/**
 * Result of importing a mod from a zip archive.
 */
export type ImportResult = { mod_record: ModRecord; file_count: number; sub_mods: SubModRecord[]; has_recognized_files: boolean }
/**
 * A journal entry returned by scan_incomplete().
 */
export type IncompleteJournalEntry = { id: number; mod_id: number; operation: string; files: FilePair[] }
export type IntegrityScanResult = { missing_from_game: ModRecord[]; missing_from_staging: ModRecord[]; incomplete_journals: IncompleteJournalEntry[] }
/**
 * Input for a single loose file: where it comes from, where it goes in the game tree, and its name.
 */
export type LooseFileInput = { source_path: string; destination_path: string; file_name: string }
export type ModRecord = { id: number; game_id: number; name: string; enabled: boolean; staged_path: string; mod_type: string }
export type ProfileRecord = { id: number; game_id: number; name: string; created_at: number; updated_at: number }
export type SubModRecord = { id: number; mod_id: number; name: string; folder_name: string; enabled: boolean; user_enabled: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
